### ISSUE TITLE
Remove Polylang from PHPStan config

### ISSUE THREAD

**Issue by Chouby** [polylang/fse-classic#7]
This plugin doesn't require Polylang to work, thus we don't need:
```
		"wpsyntex/polylang-phpstan": "dev-master",
		"wpsyntex/polylang-stubs": "dev-master"
```
in `composer.json`.
I suggest to replace it by:
```
	"szepeviktor/phpstan-wordpress": "^1.0"
```
and to adapt the phpstan config.

**Comment by Hug0-Drelon** [comment]
Indeed, I don't kwon why we didn't think about it earlier...
