### ISSUE TITLE
Move plugin version only to boostrap

### ISSUE THREAD

**Issue by Chouby** [polylang/fse-classic#8]
The plugin version is currently in two files:
- In the [plugin header](https://github.com/polylang/legacy-features-for-fse/blob/999bd1c43683d25c134109812da5942919262aa5/legacy-features-fse.php#L14) in the boostrap.
- As [a constant](https://github.com/polylang/legacy-features-for-fse/blob/999bd1c43683d25c134109812da5942919262aa5/src/Plugin.php#L25) in the min plugin file.

I suggest to move the constant to the bootstrap, so that the version is managed in only one file. This will be easier to maintain and prevent mistakes.

**Comment by Hug0-Drelon** [comment]
Good idea!
